apiVersion: v1
kind: Service
metadata:
  name:  helm-demo-{{ .Values.app }}-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: {{ .Values.app }}
    env: {{ .Values.environment }}